version: '3.8'

services:
  user:
    build:
      context: ./services/userService
    ports:
      - "5001:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - inner-net


  message:
    build: 
      context: ./services/messageService
    ports:
      - "5002:80"
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - inner-net


networks:
  inner-net:
    name: inner-net
  